#ifndef __MINDCONTROL_COMMANDS_H__
#define __MINDCONTROL_COMMANDS_H__

#define COMMAND_CURSOR_UPDATE "CURS"
#define COMMAND_RETURN "RETN"
#define COMMAND_CURSOR_TO "CURT"
#define COMMAND_SCROLL "SCRL"
#define COMMAND_LEFT_DOWN "LCKD"
#define COMMAND_LEFT_UP "LCKU"
#define COMMAND_RIGHT_DOWN "RCKD"
#define COMMAND_RIGHT_UP "RCKU"
#define COMMAND_KEYPRESS "KPRS"
#define COMMAND_KEYRELEASE "KRLS"

#endif