#ifndef __MINDCONTROL_COMMANDS_H__
#define __MINDCONTROL_COMMANDS_H__

#include <stdint.h>

#define COMMAND(com) (*(uint32_t*)com)

#define COMMAND_CURSOR_UPDATE "CURS"
#define COMMAND_VALUE_CURSOR_UPDATE 0x53525543
#define COMMAND_RETURN "RETN"
#define COMMAND_VALUE_RETURN 0x4e544552
#define COMMAND_NEXT_SCREEN "NXSN"
#define COMMAND_VALUE_NEXT_SCREEN 0x4e53584e
#define COMMAND_CURSOR_TO "CURT"
#define COMMAND_VALUE_CURSOR_TO 0x54525543
#define COMMAND_SCROLL "SCRL"
#define COMMAND_VALUE_SCROLL 0x4c524353
#define COMMAND_LEFT_DOWN "LCKD"
#define COMMAND_VALUE_LEFT_DOWN 0x444b434c
#define COMMAND_LEFT_UP "LCKU"
#define COMMAND_VALUE_LEFT_UP 0x554b434c
#define COMMAND_RIGHT_DOWN "RCKD"
#define COMMAND_VALUE_RIGHT_DOWN 0x444b4352
#define COMMAND_RIGHT_UP "RCKU"
#define COMMAND_VALUE_RIGHT_UP 0x554b4352
#define COMMAND_KEYPRESS "KPRS"
#define COMMAND_VALUE_KEYPRESS 0x5352504b
#define COMMAND_KEYRELEASE "KRLS"
#define COMMAND_VALUE_KEYRELEASE 0x534c524b
#define COMMAND_UPDATE_CLIPBOARD "UCLP"
#define COMMAND_VALUE_UPDATE_CLIPBOARD 0x504c4355
#define COMMAND_GO_BY_EDGE_AT "GBEA"
#define COMMAND_VALUE_GO_BY_EDGE_AT 0x41454247
#define COMMAND_TRANSFER_FILE "TRFL"
#define COMMAND_VALUE_TRANSFER_FILE 0x4c465254

#endif